version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: aggo-postgres
    environment:
      POSTGRES_DB: aggo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: